name: Node.js Package

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions: {}

concurrency:
  group: cd-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build npm bundle
    runs-on: ubuntu-24.04

    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          persist-credentials: false

      - name: Install NodeJS
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Get package version
        id: version
        run: |
          PKG_VERSION=$(jq -r '.version' package.json)
          if [[ -z "$PKG_VERSION" || "$PKG_VERSION" == "null" ]]; then
            echo "::error::Could not read .version from package.json"
            exit 1
          fi
          echo "package_version=$PKG_VERSION" >> "$GITHUB_OUTPUT"

      - name: Run build
        run: npm run build

      - name: Upload build artifact
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: passwordless-nodejs-${{ steps.version.outputs.package_version }}-npm-build
          path: "*dist/**"
          if-no-files-found: error

